version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - mongodb_network
    restart: always

  python-app:
    build:
      context: ./python_app  # Path to the Python app directory
    container_name: python_container
    depends_on:
      - mongodb
    volumes:
      - ./python_app/data_generator.py:/app/data_generator.py
    networks:
      - mongodb_network
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - mongodb_network
    restart: always

  mongodb-exporter:
    build:
      context: ./python_exporter  # Path to the Python exporter directory (where Dockerfile is)
    container_name: mongo_exporter
    restart: always
    ports:
      - "8000:8000"  # Port for Prometheus to scrape metrics
    networks:
      - mongodb_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - mongodb_network

volumes:
  mongodb_data:
  grafana_data:

networks:
  mongodb_network:
